name: Auto Pull Request

on:
  workflow_dispatch:
  push:
    branches:
      - "auto-pr/**"

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Auto PR update"
          branch: "auto-pr-generated"
          delete-branch: true
          title: "Auto PR from ChatGPT"
          body: "New auto-commit from chatGPT"

